services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]

  demo.user_navigation_listener:
    class: "Nerdlichter\\DemoBundle\\EventListener\\UserNavigationListener"
    arguments:
      - "@request_stack"
      - "@router"
      - "@service_container"
